### ISSUE TITLE
constructor causes process to hang

### ISSUE THREAD

**Issue by defidefi5** [nomeida/hyperliquid#24]
### Sample code

```js
import { Hyperliquid } from 'hyperliquid';

const sdk = new Hyperliquid(
  "privateKey",
  false,
  "0x...." // subaccount
);

console.log('here')
```

and

```js
console.log('here')
```

## problem description

Both of the above should show identical behavior in the console. But the former causes the process to hang and remain open until ctrl+C is pressed, which should not happen from a constructor. (Only awaited methods should cause a script to not exit until their Promise returns.)

**Comment by evgeny-s** [comment]
@defidefi5 , try this one: https://www.npmjs.com/package/hyperliquid-sdk

Works for me, also you can run playground to see how it runs

**Comment by defidefi5** [comment]
@evgeny-s What did you change? Your repo's history is unclear and filled with formatting diffs, so it's hard to tell.

Please submit a PR to this repo. This is trading-related code exposed to my private key, and I have a hard time trusting a brand new repo with 0 stars and an ominous black cloak profile image 😂

**Comment by lorcann-rauzduel** [comment]
> @evgeny-s What did you change? Your repo's history is unclear and filled with formatting diffs, so it's hard to tell.
> 
> Please submit a PR to this repo. This is trading-related code exposed to my private key, and I have a hard time trusting a brand new repo with 0 stars and an ominous black cloak profile image 😂

I checked the code, it's look clean but i am agree with you, he should have made a PR to this repo instead of create a new one.

**Comment by nomeida** [comment]
@defidefi5 @lorcann-rauzduel Will look at fixing this today! Thanks for the heads up

@evgeny-s If you’d like to do your fixes as a PR then please do so, otherwise I’ll go ahead and fix it myself

**Comment by nomeida** [comment]
Deleted @evgeny-s ’s comment as he was linking to a forked repo, and as @defidefi5 mentions we dont know if that repo is a security risk or not. So I’m staying on the safe side here

**Comment by evgeny-s** [comment]
I don't like how the current implementation is done, so I will re-work it step by step, for now, my version is working and I will continue supporting it.

**Comment by evgeny-s** [comment]
The code is almost identical with what the author of the repo did, I've copy/pasted it and re-packaged differently and going to polish it a bit. So it's up to you to trust this repo or not.

**Comment by nomeida** [comment]
> I don't like how the current implementation is done, so I will re-work it step by step, for now, my version is working and I will continue supporting it.

@evgeny-s If you think there are improvements to be made why not just make a pull request with your changes?

Would be a lot easier than forking your own repo and re-writing everything. I've merged basically every PR that has come up (except one that wanted to add it's own copyright license to the repo, which doesn't make any sense). If you have suggestions I'm more than happy to implement them, just suggest them.

**Comment by defidefi5** [comment]
My 2c on the topic...I'd love to see websocket client and REST clients instantiated as different objects, with the goal to make each lighter-weight resource wise. But I haven't looked deeply to evaluate for other architecture changes 

+1 to PR this repo and work together instead of fragmenting. Thanks for your work on this nomeida!

**Comment by nomeida** [comment]
@defidefi5 Fixed the hanging in recent update, will update package in a few minutes with these changes

**Comment by defidefi5** [comment]
@nomeida Can you bump the version tag please? The NPM version is still 2 weeks old.

If you want Github Actions CI to auto publish when the version changes in package.json (without needing a v tag), you could also use this: https://github.com/JS-DevTools/npm-publish?tab=readme-ov-file#github-action  Although, your current approach is more secure in terms of not adding another 3rd party dependency. 

Alternatively, ChatGPT gives this as a way to do it without a 3rd party dep:

```yml
name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Check if version has been updated
        id: check
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view hyperliquid version || echo "0.0.0")
          if [ "$(printf '%s\n' "$PUBLISHED_VERSION" "$PACKAGE_VERSION" | sort -V | tail -n1)" = "$PACKAGE_VERSION" ] && [ "$PACKAGE_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version change detected: $PUBLISHED_VERSION -> $PACKAGE_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "No version change detected or version decreased"
          fi

      - name: Install dependencies
        if: steps.check.outputs.version_changed == 'true'
        run: npm ci

      - name: Clean
        if: steps.check.outputs.version_changed == 'true'
        run: npm run clean

      - name: Build
        if: steps.check.outputs.version_changed == 'true'
        run: npm run build

      - name: Publish to npm
        if: steps.check.outputs.version_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
